<template>
  <article class="row">
    <div class="col-12 col-lg-6">
      <h2 class="text-left h2">¿Por qué existe Prestamype?</h2>
      <p class="text-justify p">
        En el Perú, las micro y pequeñas empresas representan más del 99% de las empresas y generan 50% del empleo, sin embargo, muchas afrontan dificultades para acceder al financiamiento que necesitan para crecer. Además, éste suele ser lento y burocrático, en contraste con las necesidades de las MYPES.
      </p>
      <p class="text-justify p">
        Por otro lado, las personas que lograron generar ahorros no reciben un buen retorno por ellos, o se exponen a inversiones riesgosas, mientras que los intermediarios financieros tradicionales se quedan con la mayor parte de las ganancias y trasladan sus altos costos operativos a los inversionistas.
      </p>
      <p class="text-justify p">
        Prestamype promueve una mejor manera de invertir para todos, que brinde una nueva opción de financiamiento para los empresarios de forma ágil y personalizada y permita a los inversionistas acceder tasas de retorno atractivas con la mayor seguridad, gracias el respaldo de una garantía inmobiliaria.
      </p>
    </div>
    <div class="col-12 col-lg-6">
      <div>
        <h2 class="text-left h2">¿Qué hace Prestamype?</h2>
        <p class="text-justify p">
          Prestamype conecta micro y pequeños empresarios que necesitan un préstamo para su negocio con inversionistas que buscan un mayor retorno de sus ahorros.
        </p>
      </div>
      <div>
        <h2 class="text-left h2">Registrados en la SBS</h2>
        <p class="text-justify p">
          Prestamype es una marca de P2P Finance Consulting SAC con RUC 20601802296, empresa registrada en la Superintendencia de Banca y Seguros (SBS – Resolución N° 03470).
        </p>
        <a href="https://www.slideshare.net/Prestamype/prestamype-sbs" target="_blank" class="mb-5">Ver documento</a>
      </div>
    </div>
  </article>
</template>
<script>

</script>
<style scoped>
div>.h2 {
  font-size: 23px;
  font-weight: 700;
  margin-bottom: 30px;
}

.p {
  font-size: 16px;
  font-weight: 500;
  color: #494949;
}

div>a {
  color: #01cd78!important;
  font-weight: 700;
  border-bottom: 1px solid #01cd78;
}
</style>


